' connections/research.puml
' Research relationships among existing components

"Corpus Explorer UI" --> "Training Corpus"
"Corpus Explorer UI" --> "TEI Repository"

"Training Corpus" --> "MacBERTh NLP Model"
"TEI Repository" --> "MacBERTh NLP Model"

"Statistics + Graphing Tools" --> "Corpus Explorer UI"
"Novelty Detection" --> "MacBERTh NLP Model"
