# tier1/tier1_phrases2events.py

from __future__ import annotations

import argparse
import os
import time
import unicodedata
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch

from lib.corpus_config import (
    CONCEPT_SETS,
    PHRASE_SETS,
    EMBED_BATCH_SIZE,
    LANCE_INDEXES_DIR,
)
from lib.corpus_db import get_connection
from lib.corpus_logging import logger
from lib.macberth import load_macberth
from lib.stopwords_min import STOPWORDS
from tier1.corpus_processor import NEIGHBOUR_RADIUS
from tier1.db_observation_backend import (
    allocate_event_ids,
    insert_events,
    create_events_table,
)
from tier1.vector_writer import VectorWriter

os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
os.environ.setdefault("OMP_NUM_THREADS", "4")
os.environ.setdefault("MKL_NUM_THREADS", "4")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "2")


# ---------------------------------------------------------------------------
# Window / scale configuration
# ---------------------------------------------------------------------------

WINDOW_CONFIGS = (
    {"name": "local", "size": 128, "stride": 64},
    {"name": "medium", "size": 256, "stride": 128},
    {"name": "broad", "size": 512, "stride": 384},
)

SCALE_NAMES = tuple(config["name"] for config in WINDOW_CONFIGS)

# Broad is retained in the schema/provenance but is not generated by default.
ACTIVE_SCALES = ("local", "medium")

LANCE_MODEL_NAME = "macberth"
LANCE_BUCKET_SIZE = 50


# ---------------------------------------------------------------------------
# Token helpers
# ---------------------------------------------------------------------------

def normalise_token(token: str) -> str:
    return unicodedata.normalize("NFKC", token).strip().lower()


def is_punctuation(token: str) -> bool:
    value = normalise_token(token)

    return bool(value) and all(
        unicodedata.category(char).startswith("P")
        for char in value
    )


def is_stopword(token: str) -> bool:
    return normalise_token(token) in STOPWORDS


def is_storable_event(token: str) -> bool:
    return not is_stopword(token) and not is_punctuation(token)


# ---------------------------------------------------------------------------
# Seed / phrase forms
# ---------------------------------------------------------------------------

def seed_forms() -> set[str]:
    forms: set[str] = set()

    for rule in CONCEPT_SETS.values():
        forms.update(
            normalise_token(form)
            for form in rule["forms"]
        )

    return forms


def false_positive_forms() -> set[str]:
    forms: set[str] = set()

    for rule in CONCEPT_SETS.values():
        forms.update(
            normalise_token(form)
            for form in rule["false_positives"]
        )

    return forms


SEED_FORMS = seed_forms()
FALSE_POSITIVE_FORMS = false_positive_forms()


def is_seed(token: str) -> bool:
    value = normalise_token(token)

    return (
        value in SEED_FORMS
        and value not in FALSE_POSITIVE_FORMS
    )


def phrase_forms() -> list[tuple[str, ...]]:
    forms: list[tuple[str, ...]] = []

    for phrase_set in PHRASE_SETS.values():
        for phrase in phrase_set:
            if isinstance(phrase, str):
                tokens = tuple(
                    normalise_token(token)
                    for token in phrase.split()
                    if token.strip()
                )
            else:
                tokens = tuple(
                    normalise_token(token)
                    for token in phrase
                )

            if tokens:
                forms.append(tokens)

    return forms


PHRASE_FORMS = phrase_forms()


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class TokenRow:
    corpus: str
    doc_id: str
    token_idx: int
    token: str
    pub_year: int | None


@dataclass(slots=True)
class EmbeddedVector:
    vector: np.ndarray
    window_id: int
    window_token_pos: int


@dataclass(slots=True)
class Observation:
    event_id: int | None
    corpus: str
    doc_id: str
    token: str
    token_idx: int
    pub_year: int | None

    local_window_id: int | None
    local_window_token_pos: int | None

    medium_window_id: int | None
    medium_window_token_pos: int | None

    broad_window_id: int | None
    broad_window_token_pos: int | None


@dataclass(slots=True)
class EmbeddedObservation:
    observation: Observation
    vectors: dict[str, np.ndarray]


@dataclass(slots=True)
class SpanObservation:
    event_id: int | None
    corpus: str
    doc_id: str
    phrase: str
    token_idx: int
    span_end_idx: int
    pub_year: int | None

    local_window_id: int | None
    local_window_token_pos: int | None

    medium_window_id: int | None
    medium_window_token_pos: int | None

    broad_window_id: int | None
    broad_window_token_pos: int | None


@dataclass(slots=True)
class EmbeddedSpanObservation:
    observation: SpanObservation
    vectors: dict[str, np.ndarray]


AnyEmbedded = EmbeddedObservation | EmbeddedSpanObservation


@dataclass(slots=True)
class DocBuffer:
    corpus: str
    doc_id: str
    pub_year: int | None
    rows: list[TokenRow]

    @property
    def tokens(self) -> list[str]:
        return [row.token for row in self.rows]

    def __bool__(self) -> bool:
        return bool(self.rows)


# ---------------------------------------------------------------------------
# Existing-event helpers
# ---------------------------------------------------------------------------

def existing_event_documents(
    conn,
    *,
    corpus: str,
    phrases: bool = False,
) -> set[str]:
    """
    Return documents which already have observations of the requested type.

    Token observations:
        span_end_idx IS NULL

    Phrase observations:
        span_end_idx IS NOT NULL

    This deliberately keeps token and phrase completion independent.
    """

    span_clause = (
        "e.span_end_idx IS NOT NULL"
        if phrases
        else "e.span_end_idx IS NULL"
    )

    with conn.cursor() as cur:
        cur.execute(
            f"""
            SELECT DISTINCT e.doc_id
            FROM events AS e
            WHERE e.corpus = %s
              AND {span_clause}
            """,
            (corpus,),
        )

        return {
            row[0]
            for row in cur.fetchall()
        }


# ---------------------------------------------------------------------------
# MacBERTh
# ---------------------------------------------------------------------------

class MacBERThPipeline:
    def __init__(
        self,
        mac,
        *,
        batch_size: int = EMBED_BATCH_SIZE,
        mask_targets: bool = False,
    ) -> None:
        self.mac = mac
        self.tokenizer = mac.tokenizer
        self.model = mac.model
        self.device = mac.device
        self.batch_size = batch_size
        self.mask_targets = mask_targets

    def embed(
        self,
        document: DocBuffer,
        target_positions: set[int],
        scales: tuple[str, ...] = ACTIVE_SCALES,
    ) -> dict[int, dict[str, EmbeddedVector]]:
        if not target_positions:
            return {}

        results: dict[int, dict[str, EmbeddedVector]] = {
            position: {}
            for position in target_positions
        }

        encoded = self.tokenizer(
            document.tokens,
            is_split_into_words=True,
            truncation=False,
            return_tensors="pt",
        )

        input_ids = encoded["input_ids"][0].tolist()
        attention_mask = encoded["attention_mask"][0].tolist()
        word_ids = encoded.word_ids()

        if word_ids is None:
            raise RuntimeError(
                "MacBERTh tokenizer did not return word_ids; "
                "cannot align token occurrences to hidden states."
            )

        for config in WINDOW_CONFIGS:
            if config["name"] not in scales:
                continue

            jobs = self._make_jobs(
                input_ids=input_ids,
                attention_mask=attention_mask,
                word_ids=word_ids,
                target_positions=target_positions,
                window_size=config["size"],
                stride=config["stride"],
            )

            for offset in range(0, len(jobs), self.batch_size):
                batch = jobs[offset:offset + self.batch_size]
                hidden = self._forward(batch)

                for job, vectors in zip(batch, hidden):
                    for target, vector in zip(
                        job["targets"],
                        vectors,
                    ):
                        word_position = target["word_position"]

                        if word_position not in results:
                            raise RuntimeError(
                                "Embedding returned a target position "
                                f"that was not requested: {word_position}"
                            )

                        results[word_position][config["name"]] = (
                            EmbeddedVector(
                                vector=vector,
                                window_id=job["window_id"],
                                window_token_pos=target["encoded_position"],
                            )
                        )

        missing = []

        for position in sorted(target_positions):
            missing_scales = [
                scale
                for scale in scales
                if scale not in results[position]
            ]

            if missing_scales:
                missing.append(
                    (
                        position,
                        document.rows[position].token,
                        missing_scales,
                    )
                )

        if missing:
            logger.error(
                "[tier1] incomplete embeddings: %d observations",
                len(missing),
            )

            for position, token, missing_scales in missing[:20]:
                logger.error(
                    "[tier1] position=%d token=%r missing=%s",
                    position,
                    token,
                    missing_scales,
                )

            raise RuntimeError(
                f"{len(missing)} observations did not receive "
                "all requested embeddings."
            )

        return results

    def embed_span(
        self,
        document: DocBuffer,
        start_position: int,
        end_position: int,
        scales: tuple[str, ...] = ACTIVE_SCALES,
    ) -> dict[str, EmbeddedVector]:
        """
        Embed a contiguous phrase span.

        The phrase vector is the mean of the contextual token vectors for
        the complete span. Provenance is anchored to the first token in
        the span's generated MacBERTh window.

        `end_position` is exclusive.
        """

        if not (
            0 <= start_position < end_position <= len(document.rows)
        ):
            raise ValueError(
                f"Invalid span {start_position}:{end_position}"
            )

        positions = set(
            range(start_position, end_position)
        )

        embedded = self.embed(
            document,
            positions,
            scales=scales,
        )

        results: dict[str, EmbeddedVector] = {}

        for scale in scales:
            vectors = [
                embedded[position][scale].vector
                for position in range(
                    start_position,
                    end_position,
                )
            ]

            if not vectors:
                raise RuntimeError(
                    f"No vectors generated for span "
                    f"{start_position}:{end_position}"
                )

            vector = np.mean(
                np.stack(vectors),
                axis=0,
            ).astype(np.float32, copy=False)

            first = embedded[start_position][scale]

            results[scale] = EmbeddedVector(
                vector=vector,
                window_id=first.window_id,
                window_token_pos=first.window_token_pos,
            )

        return results

    def _make_jobs(
        self,
        *,
        input_ids: list[int],
        attention_mask: list[int],
        word_ids: list[int | None],
        target_positions: set[int],
        window_size: int,
        stride: int,
    ) -> list[dict]:

        word_count = (
            max(
                word_id
                for word_id in word_ids
                if word_id is not None
            )
            + 1
        )

        word_spans: list[tuple[int, int]] = []
        current_word = None
        current_start = None

        for encoded_position, word_id in enumerate(word_ids):
            if word_id is None:
                continue

            if word_id != current_word:
                if current_word is not None:
                    word_spans.append(
                        (
                            current_start,
                            encoded_position,
                        )
                    )

                current_word = word_id
                current_start = encoded_position

        if current_word is not None:
            word_spans.append(
                (
                    current_start,
                    len(word_ids),
                )
            )

        if len(word_spans) != word_count:
            raise RuntimeError(
                "MacBERTh word alignment is incomplete: "
                f"expected {word_count} corpus tokens, "
                f"got {len(word_spans)} encoded spans."
            )

        jobs: list[dict] = []
        covered_targets: set[int] = set()

        start_word = 0

        while start_word < word_count:
            end_word = min(
                word_count,
                start_word + window_size,
            )

            candidate_targets = sorted(
                position
                for position in target_positions
                if start_word <= position < end_word
            )

            if candidate_targets:
                group: list[int] = []

                for target in candidate_targets:
                    if not group:
                        group.append(target)
                        continue

                    group_start = word_spans[group[0]][0]
                    group_end = word_spans[target][1]

                    if group_end - group_start <= 512:
                        group.append(target)
                    else:
                        self._append_job(
                            jobs=jobs,
                            covered_targets=covered_targets,
                            input_ids=input_ids,
                            attention_mask=attention_mask,
                            word_ids=word_ids,
                            word_spans=word_spans,
                            target_positions=group,
                            context_start_word=start_word,
                            context_end_word=end_word,
                        )

                        group = [target]

                if group:
                    self._append_job(
                        jobs=jobs,
                        covered_targets=covered_targets,
                        input_ids=input_ids,
                        attention_mask=attention_mask,
                        word_ids=word_ids,
                        word_spans=word_spans,
                        target_positions=group,
                        context_start_word=start_word,
                        context_end_word=end_word,
                    )

            if start_word + stride >= word_count:
                break

            start_word += stride

        missing_targets = target_positions - covered_targets

        if missing_targets:
            raise RuntimeError(
                "Some target observations were not assigned to "
                f"a MacBERTh job: {sorted(missing_targets)[:20]}"
            )

        return jobs

    def _append_job(
        self,
        *,
        jobs: list[dict],
        covered_targets: set[int],
        input_ids: list[int],
        attention_mask: list[int],
        word_ids: list[int | None],
        word_spans: list[tuple[int, int]],
        target_positions: list[int],
        context_start_word: int,
        context_end_word: int,
    ) -> None:

        target_start_word = target_positions[0]
        target_end_word = target_positions[-1] + 1

        context_start = word_spans[
            context_start_word
        ][0]

        context_end = word_spans[
            context_end_word - 1
        ][1]

        target_start = word_spans[
            target_start_word
        ][0]

        target_end = word_spans[
            target_end_word - 1
        ][1]

        target_span = target_end - target_start

        if target_span > 512:
            raise RuntimeError(
                "A target group exceeds MacBERTh's 512-position "
                f"limit: targets={target_start_word}:"
                f"{target_end_word}, encoded_length={target_span}"
            )

        available_length = context_end - context_start

        if available_length > 512:
            desired_start = target_start - (
                512 - target_span
            ) // 2

            encoded_start = max(
                context_start,
                desired_start,
            )

            encoded_end = min(
                context_end,
                encoded_start + 512,
            )

            if encoded_end - encoded_start < 512:
                encoded_start = max(
                    context_start,
                    encoded_end - 512,
                )
        else:
            encoded_start = context_start
            encoded_end = context_end

        if not (
            encoded_start <= target_start
            and target_end <= encoded_end
        ):
            raise RuntimeError(
                "Constructed MacBERTh context does not contain "
                f"all targets: targets={target_start_word}:"
                f"{target_end_word}, "
                f"context={context_start_word}:"
                f"{context_end_word}"
            )

        relative_word_ids = word_ids[
            encoded_start:encoded_end
        ]

        window_ids = input_ids[
            encoded_start:encoded_end
        ].copy()

        window_mask = attention_mask[
            encoded_start:encoded_end
        ]

        target_positions_in_window = []

        for word_position in target_positions:
            try:
                relative = relative_word_ids.index(
                    word_position
                )
            except ValueError as exc:
                raise RuntimeError(
                    "Target disappeared from its MacBERTh "
                    f"window: word_position={word_position}"
                ) from exc

            target_positions_in_window.append(
                {
                    "word_position": word_position,
                    "encoded_position": relative,
                }
            )

            if self.mask_targets:
                mask_token_id = self.tokenizer.mask_token_id

                if mask_token_id is None:
                    raise RuntimeError(
                        "MacBERTh tokenizer has no mask token."
                    )

                # Mask every wordpiece belonging to the target.
                for i, wid in enumerate(relative_word_ids):
                    if wid == word_position:
                        window_ids[i] = mask_token_id

        jobs.append(
            {
                "input_ids": window_ids,
                "attention_mask": window_mask,
                "window_id": context_start_word,
                "targets": target_positions_in_window,
            }
        )

        covered_targets.update(target_positions)

    def _forward(
        self,
        jobs: list[dict],
    ) -> list[list[np.ndarray]]:

        if not jobs:
            return []

        max_length = max(
            len(job["input_ids"])
            for job in jobs
        )

        if max_length > 512:
            raise RuntimeError(
                f"Prepared MacBERTh batch exceeds 512 tokens: "
                f"{max_length}"
            )

        pad_token_id = self.tokenizer.pad_token_id

        if pad_token_id is None:
            raise RuntimeError(
                "MacBERTh tokenizer has no pad token."
            )

        input_ids = []
        attention_masks = []

        for job in jobs:
            padding = max_length - len(job["input_ids"])

            input_ids.append(
                job["input_ids"] + [pad_token_id] * padding
            )

            attention_masks.append(
                job["attention_mask"] + [0] * padding
            )

        input_tensor = torch.tensor(
            input_ids,
            dtype=torch.long,
            device=self.device,
        )

        attention_tensor = torch.tensor(
            attention_masks,
            dtype=torch.long,
            device=self.device,
        )

        with torch.inference_mode():
            output = self.mac.encode(
                input_ids=input_tensor,
                attention_mask=attention_tensor,
                return_dict=True,
            )

        hidden = output.last_hidden_state.cpu().numpy()

        return [
            [
                hidden[
                    batch_index,
                    target["encoded_position"],
                ].astype(np.float32, copy=False)
                for target in job["targets"]
            ]
            for batch_index, job in enumerate(jobs)
        ]


# ---------------------------------------------------------------------------
# Event writer
# ---------------------------------------------------------------------------

class EventWriter:
    """
    Owns PostgreSQL event provenance and delegates vector persistence to
    VectorWriter.

    Token and phrase observations share the event table and Lance event
    space, but retain distinct PostgreSQL provenance through span_end_idx.
    """

    def __init__(
        self,
        conn,
        lance_root: Path,
    ) -> None:
        self.conn = conn
        self.lance_root = lance_root

        self.vector_writers: dict[str, VectorWriter] = {
            scale: VectorWriter(
                lance_root,
                scale=scale,
                model_name=LANCE_MODEL_NAME,
                bucket_size=LANCE_BUCKET_SIZE,
            )
            for scale in ACTIVE_SCALES
        }

    def _writer_for_scale(
        self,
        scale: str,
    ) -> VectorWriter:
        writer = self.vector_writers.get(scale)

        if writer is None:
            writer = VectorWriter(
                self.lance_root,
                scale=scale,
                model_name=LANCE_MODEL_NAME,
                bucket_size=LANCE_BUCKET_SIZE,
            )

            self.vector_writers[scale] = writer

        return writer

    def purge_orphans(
        self,
        conn,
        *,
        year_range=None,
        apply=False,
    ):
        return {
            scale: writer.purge_orphans(
                conn,
                year_range=year_range,
                apply=apply,
            )
            for scale, writer in self.vector_writers.items()
        }

    def write(
        self,
        observations: list[AnyEmbedded],
    ) -> int:
        if not observations:
            return 0

        event_ids = allocate_event_ids(
            self.conn,
            len(observations),
        )

        for embedded, event_id in zip(
            observations,
            event_ids,
        ):
            embedded.observation.event_id = event_id

        self._write_postgres(observations)
        self._write_lance(observations)

        return len(observations)

    def repair_lance(
        self,
        observations: list[AnyEmbedded],
    ) -> int:
        if not observations:
            return 0

        self._resolve_repair_event_ids(observations)

        return self._write_lance(observations)

    def index_existing_tables(self) -> None:
        for writer in self.vector_writers.values():
            writer.index_existing_tables()

    def build_indexes(self) -> None:
        for writer in self.vector_writers.values():
            writer.build_indexes()

    def _write_postgres(
        self,
        observations: list[AnyEmbedded],
    ) -> None:
        if not observations:
            return

        if any(
            embedded.observation.event_id is None
            for embedded in observations
        ):
            raise RuntimeError(
                "Cannot persist observations before PostgreSQL "
                "event IDs have been allocated."
            )

        is_phrase = isinstance(
            observations[0],
            EmbeddedSpanObservation,
        )

        if any(
            isinstance(embedded, EmbeddedSpanObservation) != is_phrase
            for embedded in observations
        ):
            raise RuntimeError( "Cannot write mixed token and phrase observations in a single batch." )


        for item in observations:
            obs = item.observation
            if obs.token_idx is None:
                raise RuntimeError(
                    f"NULL token_idx before PostgreSQL: "
                    f"event_id={obs.event_id!r}, "
                    f"corpus={obs.corpus!r}, "
                    f"doc_id={obs.doc_id!r}, "
                    f"token={obs.token!r}, "
                    f"pub_year={obs.pub_year!r}, "
                    f"observation={obs!r}"
                )

        if is_phrase:
            phrase_observations = [
                embedded
                for embedded in observations
                if isinstance(embedded, EmbeddedSpanObservation)
            ]

            insert_events(
                self.conn,
                event_id=[o.observation.event_id for o in observations],
                corpus=[o.observation.corpus for o in observations],
                doc_id=[o.observation.doc_id for o in observations],
                token=[o.observation.token for o in observations],
                token_idx=[o.observation.token_idx for o in observations],
                span_end_idx=[o.observation.span_end_idx for o in observations],
                pub_year=[o.observation.pub_year for o in observations],
                local_window_id=[o.observation.local_window_id for o in observations],
                local_window_token_pos=[
                    o.observation.local_window_token_pos for o in observations
                ],
                medium_window_id=[o.observation.medium_window_id for o in observations],
                medium_window_token_pos=[
                    o.observation.medium_window_token_pos for o in observations
                ],
                broad_window_id=[o.observation.broad_window_id for o in observations],
                broad_window_token_pos=[
                    o.observation.broad_window_token_pos for o in observations
                ],
            )

        else:
            token_observations = [
                embedded
                for embedded in observations
                if isinstance(embedded, EmbeddedObservation)
            ]

            insert_events(
                self.conn,
                event_id=[o.observation.event_id for o in observations],
                corpus=[o.observation.corpus for o in observations],
                doc_id=[o.observation.doc_id for o in observations],
                token=[o.observation.token for o in observations],
                token_idx=[o.observation.token_idx for o in observations],
                span_end_idx=[None for _ in observations],
                pub_year=[o.observation.pub_year for o in observations],
                local_window_id=[o.observation.local_window_id for o in observations],
                local_window_token_pos=[
                    o.observation.local_window_token_pos for o in observations
                ],
                medium_window_id=[o.observation.medium_window_id for o in observations],
                medium_window_token_pos=[
                    o.observation.medium_window_token_pos for o in observations
                ],
                broad_window_id=[o.observation.broad_window_id for o in observations],
                broad_window_token_pos=[
                    o.observation.broad_window_token_pos for o in observations
                ],
            )

        self.conn.commit()

    def _write_lance(
        self,
        observations: list[AnyEmbedded],
        *,
        scales: tuple[str, ...] = ACTIVE_SCALES,
    ) -> int:

        batches: dict[
            tuple[str, int],
            list[AnyEmbedded],
        ] = defaultdict(list)

        for embedded in observations:
            observation = embedded.observation

            if observation.event_id is None:
                raise RuntimeError(
                    "Cannot write an observation to Lance without "
                    "an authoritative PostgreSQL event ID."
                )

            if observation.pub_year is None:
                raise ValueError(
                    f"Observation {observation.event_id} has no "
                    "publication year and cannot be assigned to "
                    "a chronological Lance table."
                )

            for scale in scales:
                if scale not in embedded.vectors:
                    raise RuntimeError(
                        f"Observation {observation.event_id} has no "
                        f"vector for scale {scale!r}"
                    )

                batches[
                    (scale, observation.pub_year)
                ].append(embedded)

        total_written = 0

        for (scale, pub_year), batch in batches.items():
            writer = self._writer_for_scale(scale)

            event_ids = [
                embedded.observation.event_id
                for embedded in batch
            ]

            vectors = np.stack(
                [
                    embedded.vectors[scale]
                    for embedded in batch
                ]
            )

            total_written += writer.write(
                event_ids=event_ids,
                pub_year=pub_year,
                vectors=vectors,
            )

        return total_written

    def _resolve_repair_event_ids(
        self,
        observations: list[AnyEmbedded],
    ) -> None:
        """
        Resolve repair IDs using complete observation provenance.

        Token identity:
            corpus + doc_id + token_idx + window provenance

        Phrase identity:
            corpus + doc_id + token_idx + span_end_idx +
            window provenance
        """

        for embedded in observations:
            observation = embedded.observation

            if isinstance(
                observation,
                SpanObservation,
            ):
                clauses = [
                    "corpus = %s",
                    "doc_id = %s",
                    "token_idx = %s",
                    "span_end_idx = %s",
                    "local_window_id IS NOT DISTINCT FROM %s",
                    "local_window_token_pos IS NOT DISTINCT FROM %s",
                    "medium_window_id IS NOT DISTINCT FROM %s",
                    "medium_window_token_pos IS NOT DISTINCT FROM %s",
                    "broad_window_id IS NOT DISTINCT FROM %s",
                    "broad_window_token_pos IS NOT DISTINCT FROM %s",
                ]

                params = (
                    observation.corpus,
                    observation.doc_id,
                    observation.token_idx,
                    observation.span_end_idx,
                    observation.local_window_id,
                    observation.local_window_token_pos,
                    observation.medium_window_id,
                    observation.medium_window_token_pos,
                    observation.broad_window_id,
                    observation.broad_window_token_pos,
                )

            else:
                clauses = [
                    "corpus = %s",
                    "doc_id = %s",
                    "token_idx = %s",
                    "span_end_idx IS NULL",
                    "local_window_id IS NOT DISTINCT FROM %s",
                    "local_window_token_pos IS NOT DISTINCT FROM %s",
                    "medium_window_id IS NOT DISTINCT FROM %s",
                    "medium_window_token_pos IS NOT DISTINCT FROM %s",
                    "broad_window_id IS NOT DISTINCT FROM %s",
                    "broad_window_token_pos IS NOT DISTINCT FROM %s",
                ]

                params = (
                    observation.corpus,
                    observation.doc_id,
                    observation.token_idx,
                    observation.local_window_id,
                    observation.local_window_token_pos,
                    observation.medium_window_id,
                    observation.medium_window_token_pos,
                    observation.broad_window_id,
                    observation.broad_window_token_pos,
                )

            with self.conn.cursor() as cur:
                cur.execute(
                    f""" SELECT event_id FROM events WHERE {" AND ".join(clauses)} """,
                    params,
                )

                rows = cur.fetchall()

            if not rows:
                raise RuntimeError(
                    "Lance repair could not find an existing PostgreSQL "
                    "event for observation "
                    f"{observation.corpus}/"
                    f"{observation.doc_id}/"
                    f"{observation.token_idx}"
                )

            if len(rows) > 1:
                raise RuntimeError(
                    "Lance repair found multiple PostgreSQL events for "
                    "the same complete observation provenance: "
                    f"{observation.corpus}/"
                    f"{observation.doc_id}/"
                    f"{observation.token_idx}"
                )

            observation.event_id = int(rows[0][0])


# ---------------------------------------------------------------------------
# Corpus processor
# ---------------------------------------------------------------------------

class CorpusProcessor:
    def __init__(
        self,
        conn,
        pipeline: MacBERThPipeline,
        writer: EventWriter,
        *,
        neighbour_radius: int = NEIGHBOUR_RADIUS,
        report_every: int = 25,
    ) -> None:
        self.conn = conn
        self.pipeline = pipeline
        self.writer = writer
        self.neighbour_radius = neighbour_radius
        self.report_every = report_every

    # ------------------------------------------------------------------
    # Normal token processing
    # ------------------------------------------------------------------

    def process(
        self,
        *,
        corpus: str | None = None,
        doc_id: str | None = None,
    ) -> None:

        documents = self._find_seed_documents(
            corpus=corpus,
            doc_id=doc_id,
        )

        logger.info(
            "[tier1] seed documents: %d",
            len(documents),
        )

        completed_docs_by_corpus: dict[str, set[str]] = {}

        for document_corpus, _document_id in documents:
            if document_corpus not in completed_docs_by_corpus:
                completed_docs_by_corpus[
                    document_corpus
                ] = existing_event_documents(
                    self.writer.conn,
                    corpus=document_corpus,
                    phrases=False,
                )

        for number, (
            document_corpus,
            document_id,
        ) in enumerate(
            documents,
            start=1,
        ):
            completed_docs = completed_docs_by_corpus[
                document_corpus
            ]

            if document_id in completed_docs:
                logger.info(
                    "[tier1] skipping completed token document "
                    "%s/%s",
                    document_corpus,
                    document_id,
                )
                continue

            started = time.perf_counter()

            document = self._load_document(
                document_corpus,
                document_id,
            )

            if document is None:
                continue

            seed_positions = {
                position
                for position, row in enumerate(document.rows)
                if is_seed(row.token)
            }

            if not seed_positions:
                continue

            target_positions = self._select_neighbours(
                seed_positions,
                document,
            )

            embeddings = self.pipeline.embed(
                document,
                target_positions,
            )

            observations = self._build_observations(
                document,
                target_positions,
                embeddings,
            )

            written = self.writer.write(
                observations,
            )

            elapsed = time.perf_counter() - started

            logger.info(
                "[tier1] %3d/%-3d %-4s %-15s "
                "seeds=%3d observations=%5d "
                "written=%5d elapsed=%7.2fs",
                number,
                len(documents),
                document_corpus,
                document_id,
                len(seed_positions),
                len(observations),
                written,
                elapsed,
            )

            completed_docs.add(document_id)

            if number % self.report_every == 0:
                logger.info(
                    "[tier1] processed %d documents",
                    number,
                )

    # ------------------------------------------------------------------
    # Phrase processing
    # ------------------------------------------------------------------

    def process_phrases(
        self,
        *,
        corpus: str | None = None,
        doc_id: str | None = None,
    ) -> None:

        documents = self._find_phrase_documents(
            corpus=corpus,
            doc_id=doc_id,
        )

        logger.info(
            "[tier1] phrase documents: %d",
            len(documents),
        )

        completed_docs_by_corpus: dict[str, set[str]] = {}

        for document_corpus, _document_id in documents:
            if document_corpus not in completed_docs_by_corpus:
                completed_docs_by_corpus[
                    document_corpus
                ] = existing_event_documents(
                    self.writer.conn,
                    corpus=document_corpus,
                    phrases=True,
                )

        for number, (
            document_corpus,
            document_id,
        ) in enumerate(
            documents,
            start=1,
        ):
            completed_docs = completed_docs_by_corpus[
                document_corpus
            ]

            if document_id in completed_docs:
                logger.info(
                    "[tier1] skipping completed phrase document "
                    "%s/%s",
                    document_corpus,
                    document_id,
                )
                continue

            started = time.perf_counter()

            document = self._load_document(
                document_corpus,
                document_id,
            )

            if document is None:
                continue

            spans = self._find_phrase_spans(
                document,
            )

            if not spans:
                continue

            observations: list[EmbeddedSpanObservation] = []

            for (
                start_position,
                end_position,
                phrase,
            ) in spans:

                embeddings = self.pipeline.embed_span(
                    document,
                    start_position,
                    end_position,
                )

                observations.append(
                    self._build_span_observation(
                        document=document,
                        start_position=start_position,
                        end_position=end_position,
                        phrase=phrase,
                        embeddings=embeddings,
                    )
                )

            written = self.writer.write(
                observations,
            )

            elapsed = time.perf_counter() - started

            logger.info(
                "[tier1] phrase %3d/%-3d %-4s %-15s "
                "spans=%5d written=%5d elapsed=%7.2fs",
                number,
                len(documents),
                document_corpus,
                document_id,
                len(observations),
                written,
                elapsed,
            )

            completed_docs.add(document_id)

    # ------------------------------------------------------------------
    # Repair
    # ------------------------------------------------------------------

    def repair(
        self,
        *,
        corpus: str,
        doc_id: str,
        phrases: bool = False,
    ) -> None:

        started = time.perf_counter()

        logger.info(
            "[tier1] repair: %s/%s phrases=%s",
            corpus,
            doc_id,
            phrases,
        )

        document = self._load_document(
            corpus,
            doc_id,
        )

        if document is None:
            raise RuntimeError(
                f"Document not found: {corpus}/{doc_id}"
            )

        if phrases:
            existing = self._load_phrase_events(
                corpus,
                doc_id,
            )

            spans = self._find_phrase_spans(
                document,
            )

            current = {
                (
                    start,
                    end,
                )
                for start, end, _phrase in spans
            }

            stored = {
                (
                    start,
                    end,
                )
                for start, end, _event_id in existing
            }

            if current != stored:
                raise RuntimeError(
                    f"{corpus}/{doc_id}: phrase observation set "
                    "changed since original run "
                    f"(only_current={len(current - stored)}, "
                    f"only_stored={len(stored - current)})."
                )

            observations = []

            for (
                start,
                end,
                phrase,
            ) in spans:

                embeddings = self.pipeline.embed_span(
                    document,
                    start,
                    end,
                )

                observations.append(
                    self._build_span_observation(
                        document=document,
                        start_position=start,
                        end_position=end,
                        phrase=phrase,
                        embeddings=embeddings,
                    )
                )

        else:
            existing = self._load_token_events(
                corpus,
                doc_id,
            )

            seed_positions = {
                position
                for position, row in enumerate(document.rows)
                if is_seed(row.token)
            }

            if not seed_positions:
                raise RuntimeError(
                    f"No seed occurrences found: "
                    f"{corpus}/{doc_id}"
                )

            target_positions = self._select_neighbours(
                seed_positions,
                document,
            )

            expected = {
                document.rows[position].token_idx
                for position in target_positions
            }

            stored = set(existing)

            if expected != stored:
                raise RuntimeError(
                    f"{corpus}/{doc_id}: observation set changed "
                    "since original run "
                    f"(only_expected={len(expected - stored)}, "
                    f"only_stored={len(stored - expected)}). "
                    "Check CONCEPT_SETS / --neighbour-radius."
                )

            embeddings = self.pipeline.embed(
                document,
                target_positions,
            )

            observations = self._build_observations(
                document,
                target_positions,
                embeddings,
            )

        written = self.writer.repair_lance(
            observations,
        )

        elapsed = time.perf_counter() - started

        logger.info(
            "[tier1] repair complete: %-4s %-15s "
            "observations=%5d lance_written=%5d "
            "elapsed=%7.2fs",
            corpus,
            doc_id,
            len(observations),
            written,
            elapsed,
        )

    # ------------------------------------------------------------------
    # Scale backfill
    # ------------------------------------------------------------------

    def backfill_scale(
        self,
        scale: str,
        *,
        corpus: str | None = None,
        doc_id: str | None = None,
    ) -> int:

        if scale not in SCALE_NAMES:
            raise ValueError(
                f"unknown scale {scale!r}"
            )

        writer = self.writer._writer_for_scale(
            scale,
        )

        documents = self._documents_missing_scale(
            scale,
            corpus,
            doc_id,
        )

        logger.info(
            "[backfill:%s] documents to process: %d",
            scale,
            len(documents),
        )

        for number, (
            doc_corpus,
            did,
        ) in enumerate(
            documents,
            start=1,
        ):
            started = time.perf_counter()

            n = self._backfill_document(
                doc_corpus,
                did,
                scale,
                writer,
            )

            logger.info(
                "[backfill:%s] %d/%d %s/%s "
                "events=%d elapsed=%.2fs",
                scale,
                number,
                len(documents),
                doc_corpus,
                did,
                n,
                time.perf_counter() - started,
            )

        writer.index_existing_tables()

        return len(documents)

    def _documents_missing_scale(
        self,
        scale: str,
        corpus: str | None,
        doc_id: str | None,
    ):
        clauses = [
            f"e.{scale}_window_id IS NULL",
        ]

        params: list[object] = []

        if corpus is not None:
            clauses.append(
                "e.corpus = %s"
            )
            params.append(corpus)

        if doc_id is not None:
            clauses.append(
                "e.doc_id = %s"
            )
            params.append(doc_id)

        with self.conn.cursor() as cur:
            cur.execute(
                f"""
                SELECT DISTINCT e.corpus, e.doc_id
                FROM events AS e
                WHERE {" AND ".join(clauses)}
                ORDER BY e.corpus, e.doc_id
                """,
                params,
            )

            return cur.fetchall()

    def _backfill_document(
        self,
        corpus: str,
        doc_id: str,
        scale: str,
        vector_writer: VectorWriter,
    ) -> int:

        document = self._load_document(
            corpus,
            doc_id,
        )

        if document is None:
            raise RuntimeError(
                f"Document not found: {corpus}/{doc_id}"
            )

        token_events = self._load_token_events(
            corpus,
            doc_id,
        )

        phrase_events = self._load_phrase_events(
            corpus,
            doc_id,
        )

        total = 0

        if token_events:
            total += self._backfill_token_events(
                document,
                token_events,
                scale,
                vector_writer,
            )

        if phrase_events:
            total += self._backfill_phrase_events(
                document,
                phrase_events,
                scale,
                vector_writer,
            )

        return total

    def _backfill_token_events(
        self,
        document: DocBuffer,
        events: dict[int, int],
        scale: str,
        vector_writer: VectorWriter,
    ) -> int:

        seed_positions = {
            position
            for position, row in enumerate(document.rows)
            if is_seed(row.token)
        }

        targets = self._select_neighbours(
            seed_positions,
            document,
        )

        expected = {
            document.rows[position].token_idx
            for position in targets
        }

        stored = set(events)

        if expected != stored:
            raise RuntimeError(
                f"{document.corpus}/{document.doc_id}: token "
                "observation set changed since original run "
                f"(only_expected={len(expected - stored)}, "
                f"only_stored={len(stored - expected)})."
            )

        embeddings = self.pipeline.embed(
            document,
            targets,
            scales=(scale,),
        )

        by_year: dict[
            int,
            tuple[list[int], list[np.ndarray]],
        ] = defaultdict(
            lambda: ([], [])
        )

        updates: list[
            tuple[int, int, int]
        ] = []

        for position in sorted(targets):
            row = document.rows[position]

            event_id = events[row.token_idx]

            if row.pub_year is None:
                raise RuntimeError(
                    f"{document.corpus}/{document.doc_id}: "
                    f"event {event_id} has no publication year."
                )

            embedded = embeddings[position][scale]

            ids, vectors = by_year[row.pub_year]

            ids.append(event_id)
            vectors.append(embedded.vector)

            updates.append(
                (
                    embedded.window_id,
                    embedded.window_token_pos,
                    event_id,
                )
            )

        for pub_year, (
            ids,
            vectors,
        ) in by_year.items():

            vector_writer.write(
                event_ids=ids,
                pub_year=pub_year,
                vectors=np.stack(vectors),
            )

        with self.conn.cursor() as cur:
            cur.executemany(
                f"""
                UPDATE events
                SET {scale}_window_id = %s,
                    {scale}_window_token_pos = %s
                WHERE event_id = %s
                """,
                updates,
            )

        self.conn.commit()

        return len(updates)

    def _backfill_phrase_events(
        self,
        document: DocBuffer,
        events: list[
            tuple[int, int, int]
        ],
        scale: str,
        vector_writer: VectorWriter,
    ) -> int:

        current_spans = {
            (
                start,
                end,
            ): phrase
            for start, end, phrase
            in self._find_phrase_spans(document)
        }

        stored_spans = {
            (
                start,
                end,
            )
            for start, end, _event_id
            in events
        }

        if set(current_spans) != stored_spans:
            raise RuntimeError(
                f"{document.corpus}/{document.doc_id}: phrase "
                "observation set changed since original run."
            )

        by_year: dict[
            int,
            tuple[list[int], list[np.ndarray]],
        ] = defaultdict(
            lambda: ([], [])
        )

        updates: list[
            tuple[int, int, int]
        ] = []

        for (
            start,
            end,
            event_id,
        ) in events:

            embeddings = self.pipeline.embed_span(
                document,
                start,
                end,
                scales=(scale,),
            )

            embedded = embeddings[scale]

            pub_year = document.pub_year

            if pub_year is None:
                raise RuntimeError(
                    f"{document.corpus}/{document.doc_id}: "
                    f"phrase event {event_id} has no publication year."
                )

            ids, vectors = by_year[pub_year]

            ids.append(event_id)
            vectors.append(embedded.vector)

            updates.append(
                (
                    embedded.window_id,
                    embedded.window_token_pos,
                    event_id,
                )
            )

        for pub_year, (
            ids,
            vectors,
        ) in by_year.items():

            vector_writer.write(
                event_ids=ids,
                pub_year=pub_year,
                vectors=np.stack(vectors),
            )

        with self.conn.cursor() as cur:
            cur.executemany(
                f"""
                UPDATE events
                SET {scale}_window_id = %s,
                    {scale}_window_token_pos = %s
                WHERE event_id = %s
                """,
                updates,
            )

        self.conn.commit()

        return len(updates)

    # ------------------------------------------------------------------
    # Observation builders
    # ------------------------------------------------------------------

    def _build_observations(
        self,
        document: DocBuffer,
        target_positions: set[int],
        embeddings: dict[ int, dict[str, EmbeddedVector], ],
    ) -> list[EmbeddedObservation]:

        observations: list[ EmbeddedObservation ] = []

        for position in sorted(target_positions):
            row = document.rows[position]

            vectors: dict[str, np.ndarray] = {}
            provenance: dict[ str, EmbeddedVector, ] = {}

            for scale in ACTIVE_SCALES:
                embedded = embeddings[position].get( scale )

                if embedded is None:
                    raise RuntimeError(
                        "Missing embedding provenance for "
                        f"{document.corpus}/{document.doc_id}/"
                        f"{row.token_idx}, scale={scale}"
                    )

                vectors[scale] = embedded.vector
                provenance[scale] = embedded

            local = provenance.get("local")
            medium = provenance.get("medium")
            broad = provenance.get("broad")

            observation = Observation(
                event_id=None,
                corpus=row.corpus,
                doc_id=row.doc_id,
                token=row.token,
                token_idx=row.token_idx,
                pub_year=row.pub_year,

                local_window_id=(
                    local.window_id
                    if local is not None
                    else None
                ),
                local_window_token_pos=(
                    local.window_token_pos
                    if local is not None
                    else None
                ),

                medium_window_id=(
                    medium.window_id
                    if medium is not None
                    else None
                ),
                medium_window_token_pos=(
                    medium.window_token_pos
                    if medium is not None
                    else None
                ),

                broad_window_id=(
                    broad.window_id
                    if broad is not None
                    else None
                ),
                broad_window_token_pos=(
                    broad.window_token_pos
                    if broad is not None
                    else None
                ),
            )

            observations.append(
                EmbeddedObservation(
                    observation=observation,
                    vectors=vectors,
                )
            )

        return observations

    def _build_span_observation(
        self,
        *,
        document: DocBuffer,
        start_position: int,
        end_position: int,
        phrase: str,
        embeddings: dict[
            str,
            EmbeddedVector,
        ],
    ) -> EmbeddedSpanObservation:

        start_row = document.rows[
            start_position
        ]

        vectors = {
            scale: embeddings[scale].vector
            for scale in ACTIVE_SCALES
        }

        local = embeddings.get("local")
        medium = embeddings.get("medium")
        broad = embeddings.get("broad")

        observation = SpanObservation(
            event_id=None,
            corpus=document.corpus,
            doc_id=document.doc_id,
            phrase=phrase,
            token_idx=start_row.token_idx,
            span_end_idx=document.rows[
                end_position - 1
            ].token_idx,
            pub_year=document.pub_year,

            local_window_id=(
                local.window_id
                if local is not None
                else None
            ),
            local_window_token_pos=(
                local.window_token_pos
                if local is not None
                else None
            ),

            medium_window_id=(
                medium.window_id
                if medium is not None
                else None
            ),
            medium_window_token_pos=(
                medium.window_token_pos
                if medium is not None
                else None
            ),

            broad_window_id=(
                broad.window_id
                if broad is not None
                else None
            ),
            broad_window_token_pos=(
                broad.window_token_pos
                if broad is not None
                else None
            ),
        )

        return EmbeddedSpanObservation(
            observation=observation,
            vectors=vectors,
        )

    # ------------------------------------------------------------------
    # Corpus lookup
    # ------------------------------------------------------------------

    def _find_seed_documents(
        self,
        *,
        corpus: str | None,
        doc_id: str | None,
    ) -> list[tuple[str, str]]:

        clauses = [
            "lower(t.token) = ANY(%s)",
        ]

        params: list[object] = [
            sorted(
                SEED_FORMS - FALSE_POSITIVE_FORMS
            ),
        ]

        if corpus is not None:
            clauses.append(
                "t.corpus = %s"
            )
            params.append(corpus)

        if doc_id is not None:
            clauses.append(
                "t.doc_id = %s"
            )
            params.append(doc_id)

        sql = f"""
            SELECT DISTINCT t.corpus, t.doc_id
            FROM pamphlet_tokens AS t
            WHERE {" AND ".join(clauses)}
            ORDER BY t.corpus, t.doc_id
        """

        with self.conn.cursor() as cur:
            cur.execute(
                sql,
                params,
            )

            return cur.fetchall()

    def _find_phrase_documents(
        self,
        *,
        corpus: str | None,
        doc_id: str | None,
    ) -> list[tuple[str, str]]:

        if not PHRASE_FORMS:
            return []

        first_tokens = sorted(
            {
                phrase[0]
                for phrase in PHRASE_FORMS
                if phrase
            }
        )

        clauses = [
            "lower(t.token) = ANY(%s)",
        ]

        params: list[object] = [
            first_tokens,
        ]

        if corpus is not None:
            clauses.append(
                "t.corpus = %s"
            )
            params.append(corpus)

        if doc_id is not None:
            clauses.append(
                "t.doc_id = %s"
            )
            params.append(doc_id)

        sql = f"""
            SELECT DISTINCT t.corpus, t.doc_id
            FROM pamphlet_tokens AS t
            WHERE {" AND ".join(clauses)}
            ORDER BY t.corpus, t.doc_id
        """

        with self.conn.cursor() as cur:
            cur.execute(
                sql,
                params,
            )

            return cur.fetchall()


    def _load_document(
        self,
        corpus: str,
        doc_id: str,
    ) -> DocBuffer | None:

        with self.conn.cursor() as cur:
            cur.execute(
                """
                SELECT t.corpus, t.doc_id, t.token_idx, t.token, d.pub_year
                FROM pamphlet_tokens AS t
                JOIN pamphlet_corpus AS d
                  ON d.corpus = t.corpus
                 AND d.doc_id = t.doc_id
                WHERE t.corpus = %s
                  AND t.doc_id = %s
                ORDER BY t.token_idx
                """,
                (
                    corpus,
                    doc_id,
                ),
            )

            rows = cur.fetchall()

            if not rows:
                return None

            token_rows = [
                TokenRow(
                    corpus=row[0],
                    doc_id=row[1],
                    token_idx=row[2],
                    token=row[3],
                    pub_year=row[4],
                )
                for row in rows
            ]

            for row in token_rows:
                if row.doc_id == "A01289" and row.token.lower() == "clotho":
                    logger.debug("DEBUG TOKEN ROW: %r", row)

            return DocBuffer(
                corpus=corpus,
                doc_id=doc_id,
                pub_year=token_rows[0].pub_year,
                rows=token_rows,
            )


    # ------------------------------------------------------------------
    # Phrase matching
    # ------------------------------------------------------------------

    def _find_phrase_spans(
        self,
        document: DocBuffer,
    ) -> list[
        tuple[int, int, str]
    ]:

        normalised = [
            normalise_token(row.token)
            for row in document.rows
        ]

        spans: list[
            tuple[int, int, str]
        ] = []

        for phrase in PHRASE_FORMS:
            length = len(phrase)

            if length == 0:
                continue

            for start in range(
                0,
                len(normalised) - length + 1,
            ):
                if tuple(
                    normalised[
                        start:start + length
                    ]
                ) != phrase:
                    continue

                end = start + length

                spans.append(
                    (
                        start,
                        end,
                        " ".join(phrase),
                    )
                )

        spans.sort(
            key=lambda item: (
                item[0],
                item[1],
                item[2],
            )
        )

        return spans

    # ------------------------------------------------------------------
    # Neighbours
    # ------------------------------------------------------------------

    def _select_neighbours(
        self,
        seed_positions: set[int],
        document: DocBuffer,
    ) -> set[int]:

        positions: set[int] = set()

        for seed_position in seed_positions:
            start = max(
                0,
                seed_position - self.neighbour_radius,
            )

            end = min(
                len(document.rows),
                seed_position + self.neighbour_radius + 1,
            )

            positions.update(
                position
                for position in range(
                    start,
                    end,
                )
                if (
                    position in seed_positions
                    or is_storable_event(
                        document.rows[position].token
                    )
                )
            )

        return positions

    # ------------------------------------------------------------------
    # Existing event loading
    # ------------------------------------------------------------------

    def _load_token_events(
        self,
        corpus: str,
        doc_id: str,
    ) -> dict[int, int]:

        with self.conn.cursor() as cur:
            cur.execute(
                """
                SELECT
                    token_idx,
                    event_id
                FROM events
                WHERE corpus = %s
                  AND doc_id = %s
                  AND span_end_idx IS NULL
                ORDER BY token_idx
                """,
                (
                    corpus,
                    doc_id,
                ),
            )

            rows = cur.fetchall()

        events: dict[int, int] = {}

        for token_idx, event_id in rows:
            if token_idx in events:
                raise RuntimeError(
                    f"{corpus}/{doc_id}: multiple token events "
                    f"at token_idx={token_idx}"
                )

            events[int(token_idx)] = int(event_id)

        return events

    def _load_phrase_events(
        self,
        corpus: str,
        doc_id: str,
    ) -> list[
        tuple[int, int, int]
    ]:

        with self.conn.cursor() as cur:
            cur.execute(
                """
                SELECT
                    token_idx,
                    span_end_idx,
                    event_id
                FROM events
                WHERE corpus = %s
                  AND doc_id = %s
                  AND span_end_idx IS NOT NULL
                ORDER BY token_idx, span_end_idx
                """,
                (
                    corpus,
                    doc_id,
                ),
            )

            rows = cur.fetchall()

        return [
            (
                int(token_idx),
                int(span_end_idx),
                int(event_id),
            )
            for token_idx, span_end_idx, event_id
            in rows
        ]


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def parse_repair_target(
    value: str,
) -> tuple[str, str]:

    if "/" not in value:
        raise argparse.ArgumentTypeError(
            "repair target must be CORPUS/DOC_ID"
        )

    corpus, doc_id = value.split(
        "/",
        1,
    )

    if not corpus or not doc_id:
        raise argparse.ArgumentTypeError(
            "repair target must be CORPUS/DOC_ID"
        )

    return corpus, doc_id


def repair_year_range(
    processor: CorpusProcessor,
    conn,
    start_year: int,
    end_year: int,
    corpus: str | None = None,
) -> int:

    if start_year > end_year:
        raise ValueError(
            f"start_year ({start_year}) must not exceed "
            f"end_year ({end_year})"
        )

    bucket_start = (
        start_year // LANCE_BUCKET_SIZE
    ) * LANCE_BUCKET_SIZE

    bucket_end = (
        (end_year // LANCE_BUCKET_SIZE) + 1
    ) * LANCE_BUCKET_SIZE - 1

    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT DISTINCT e.corpus, e.doc_id, e.pub_year
            FROM events AS e
            WHERE (%s::text IS NULL OR e.corpus = %s)
              AND e.pub_year BETWEEN %s AND %s
            ORDER BY
                e.pub_year,
                e.corpus,
                e.doc_id
            """,
            (
                corpus,
                corpus,
                bucket_start,
                bucket_end,
            ),
        )

        documents = cur.fetchall()

    logger.info(
        "[repair] Requested years %d-%d; repairing complete "
        "buckets %d-%d; %d documents "
        "(corpus=%s)",
        start_year,
        end_year,
        bucket_start,
        bucket_end,
        len(documents),
        corpus or "all",
    )

    repaired = 0

    for number, (
        doc_corpus,
        doc_id,
        pub_year,
    ) in enumerate(
        documents,
        start=1,
    ):
        logger.info(
            "[repair] %d/%d %s/%s "
            "(pub_year=%s)",
            number,
            len(documents),
            doc_corpus,
            doc_id,
            pub_year,
        )

        processor.repair(
            corpus=doc_corpus,
            doc_id=doc_id,
            phrases=False,
        )

        repaired += 1

    results = processor.writer.purge_orphans(
        conn,
        year_range=(
            bucket_start,
            bucket_end,
        ),
        apply=True,
    )

    logger.info( "[repair] purged orphans: %s", results, )

    logger.info(
        "[repair] Repaired %d documents "
        "for buckets %d-%d",
        repaired,
        bucket_start,
        bucket_end,
    )

    return repaired


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=( "Build Tier 1 token and phrase observations from the restricted pamphlet corpus through MacBERTh into Lance." )
    )

    parser.add_argument( "--corpus", default=None, )
    parser.add_argument( "--doc-id", default=None, )
    parser.add_argument( "--neighbour-radius", type=int, default=NEIGHBOUR_RADIUS, )
    parser.add_argument( "--lance-root", type=Path, default=Path(LANCE_INDEXES_DIR), )
    parser.add_argument( "--batch-size", type=int, default=EMBED_BATCH_SIZE, )
    parser.add_argument( "--report-every", type=int, default=1, )
    parser.add_argument( "--phrases", action="store_true", help="Process phrase observations rather than token observations.", )
    parser.add_argument( "--add-scale", choices=SCALE_NAMES, default=None, help=( "Add this scale to existing observations without creating new event IDs." ), ) parser.add_argument( "--mask", action="store_true", help=( "Replace target tokens with [MASK] before embedding." ), )
    parser.add_argument( "--index-only", action="store_true", help=( "Rebuild incomplete indexes on existing active-scale Lance tables." ), )
    parser.add_argument( "--repair", type=parse_repair_target, metavar="CORPUS/DOC_ID", help=( "Regenerate Lance vectors for one token-observation document without modifying PostgreSQL events." ), )
    parser.add_argument( "--repair-years", nargs=2, type=int, metavar=("START_YEAR", "END_YEAR"), help=( "Repair all token-observation documents in the complete 50-year Lance buckets containing this range." ), )
    parser.add_argument( "--skip-indexing", action="store_true", help=( "Skip the post-run Lance index rebuild." ), )

    args = parser.parse_args()

    if args.repair is not None and (
        args.corpus is not None
        or args.doc_id is not None
    ):
        parser.error( "--repair cannot be combined with --corpus or --doc-id" )

    if args.repair is not None and args.repair_years:
        parser.error( "--repair and --repair-years cannot be used together" )

    if args.index_only and any(
        (
            args.repair,
            args.repair_years,
            args.add_scale,
            args.phrases,
        )
    ):
        parser.error( "--index-only cannot be combined with processing, repair, or backfill options" )

    return args


def main() -> None:
    args = parse_args()

    torch.set_num_threads( int( os.environ.get( "OMP_NUM_THREADS", "4", ) ) )

    torch.set_num_interop_threads(1)
    conn = get_connection( application_name="tier1-event-creator", )
    create_events_table(conn)

    if args.index_only:
        try:
            writer = EventWriter(
                conn,
                args.lance_root,
            )

            writer.index_existing_tables()
        finally:
            conn.close()

        return

    try:
        mac = load_macberth()

        pipeline = MacBERThPipeline(
            mac,
            batch_size=args.batch_size,
            mask_targets=args.mask,
        )

        writer = EventWriter(
            conn,
            args.lance_root,
        )

        processor = CorpusProcessor(
            conn,
            pipeline,
            writer,
            neighbour_radius=args.neighbour_radius,
            report_every=args.report_every,
        )

        if args.repair:

            corpus, doc_id = args.repair

            processor.repair(
                corpus=corpus,
                doc_id=doc_id,
                phrases=args.phrases,
            )

        elif args.repair_years:

            start_year, end_year = args.repair_years

            repair_year_range(
                processor=processor,
                conn=conn,
                start_year=start_year,
                end_year=end_year,
                corpus=args.corpus,
            )

        elif args.add_scale:

            processor.backfill_scale(
                args.add_scale,
                corpus=args.corpus,
                doc_id=args.doc_id,
            )

            return

        elif args.phrases:

            processor.process_phrases(
                corpus=args.corpus,
                doc_id=args.doc_id,
            )

        else:

            processor.process(
                corpus=args.corpus,
                doc_id=args.doc_id,
            )

        if args.skip_indexing:
            logger.info(
                "[tier1] --skip-indexing set; leaving "
                "index (re)build for a later run"
            )
        else:
            writer.build_indexes()

    finally:
        conn.close()


if __name__ == "__main__":
    main()
