package "Processing_Pipeline" #Lavender {
    package "Processing_Pipeline_Images" #LavenderBlush {
        class "Image Preprocessor"
        class "OCR"
        class "TEI Converter"
    }

    package "Processing_Pipeline_TEI" #LavenderBlush {
        class "TEI Parser"
        class "Normalisation Engine"
        class "Metadata Extractor"
    }
}