package "Processing_Pipeline" #Lavender {
    class "EEBO HTML Parser"
    class "TEI Parser"
    class "Image Preprocessor"
    class "OCR"
    class "TEI Converter"
    class "Normalisation Engine"
    class "Metadata Extractor"
}