#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

(
  cd "$SCRIPT_DIR/src/fastText_eebo/sql_queries"
  sqlite3 --batch -bail ../../../../out/metadata.sqlite < index.sql
  cd $OLDPWD
)

