@startuml component_diagram_master
!include entities.puml
!include inputs.puml
!include pipeline.puml

!include connections/research.puml
!include connections/ingestion.puml
!include connections/processing.puml
!include connections/normalisation.puml
!include connections/analysis.puml

@enduml
